### ISSUE TITLE
Please open branch 14.0

### ISSUE THREAD

**Issue by yajo** [itpp-labs/misc-addons#1014]
Hello @yelizariev :wave: 

It seems you added a test using this repo back there in https://github.com/Tecnativa/doodba/pull/261, and how I'm adding support for Odoo 14.0 in https://github.com/Tecnativa/doodba/pull/323 and I'd need you to please open the 14.0 branch here so tests there pass. Would you be so kind please?

Thanks!

**Comment by yelizariev** [comment]
It also requires web_debranding be in the branch... I'll make all of it tomorrow. Thanks for you work on  supporting odoo 14
