### ISSUE TITLE
Issue in v12

### ISSUE THREAD

**Issue by midhunmadhuk** [itpp-labs/misc-addons#1092]
Issue while install in latest odoo 12 "TypeError: super(type, obj): obj must be an instance or subtype of type - - -
"

**Comment by trojikman** [comment]
Hello!
Please specify which module you are talking about?

**Comment by midhunmadhuk** [comment]
ir_attachment_S3

**Comment by trojikman** [comment]
It installs well on the latest odoo now. Maybe you have deployment issues, check installation guide here: https://github.com/itpp-labs/misc-addons/blob/12.0/ir_attachment_s3/doc/index.rst#installation
Feel free to reopen the issue if you have more details
