### ISSUE TITLE
web-debranding missing all Enterprise Links shown in Version 9

### ISSUE THREAD

**Issue by lisandi** [itpp-labs/misc-addons#122]
When clicking on those Features under Configuration Settings of Modules which are marked as Enterprise Features than they still link to Odoo and advertise the Enterprise edition. How to get rid of it?

i.e. under Projects:
Forecasts, planning and Gantt charts Enterprise
Timesheet app for Chrome/Android/iOS Enterprise

and also in other modules

Thanks

**Comment by yelizariev** [comment]
FIxed. Thank you for report
