### ISSUE TITLE
web_debranding affecting xml strings with ampersands?

### ISSUE THREAD

**Issue by GillPotter** [itpp-labs/misc-addons#147]
In Odoo 9 when web_debranding is installed it seems to affect how the ampersand appears. An example of this is the customer tabs as highlighted below-

![image](https://cloud.githubusercontent.com/assets/10741187/13350001/4dce9de4-dc75-11e5-91bb-770f595a0901.png)

It also affects the headings for Configuration / Settings in Sales and Accounting and other places.  I'm fairly sure that it is the web_debranding module causing the problem as un-installing it removes the problem.

**Comment by yelizariev** [comment]
Thanks for reporting.

@ufaks check this please

**Comment by ufaks** [comment]
I could not repeat the bug. Please check new modules versions. Perhaps the bug gone with fixes. I check it in Google Chrome and Firefox browsers.

**Comment by yelizariev** [comment]
Closed for a while

**Comment by GillPotter** [comment]
Problem has gone with a newer version of Odoo 9. Thank you for your help.
