### ISSUE TITLE
Enterprise Features still get listed

### ISSUE THREAD

**Issue by lisandi** [itpp-labs/misc-addons#149]
Enterprise Features still get listed in Configuration/Settings of:
Accounting
Sales
Point of Sales
Inventory
Project
Mass Mailing
Website Admin

Odoo Version 9 latest update from git today - 1 March 2016

**Comment by yelizariev** [comment]
are you sure, that you have latest version of web_debranding?

**Comment by yelizariev** [comment]
I've checked it here on runbot and haven't found Enterprise links:
http://01226-9-0-ceec98.runbot.it-projects.info/
admin
admin
