### ISSUE TITLE
Can not be deinstalled

### ISSUE THREAD

**Issue by lisandi** [itpp-labs/misc-addons#150]
web_debranding in its current version can't be uninstalled

openerp/modules/loading.py", line 384, in load_modules
    getattr(py_module, uninstall_hook)(cr, registry)
AttributeError: 'module' object has no attribute 'uninstall_hook'

workarround: after switching the current version with the previous version the debrand module can be deinstalled

**Comment by yelizariev** [comment]
It seems like python code was not reloaded after updating. So, restarting the server should help.
