### ISSUE TITLE
web_debranding: when installed editing company values not possible

### ISSUE THREAD

**Issue by lisandi** [itpp-labs/misc-addons#151]
When web_debranding is installed editing company values is not possible and you get directed to the website instead.

General Settings
You will find more options in your company details: address for the header and footer, overdue payments texts, etc.  -- Configure your company data

**Comment by yelizariev** [comment]
I've just tested it in 9.0 and `Configure your company data` link works.

**Comment by lisandi** [comment]
hmm have you entered a logo too and is it still there?

With kind regards,
Mit freundlichen Grüßen,
Con un cordial saludo,
Cordialement,
с сердечным приветом,
เรื่องที่เกี่ยวกับชนิด,
與親切的問候,

 _ANDI BECKER_

CEO/General Manager LisAndi Co., Ltd.

_about.me/andibecker
http://about.me/andibecker--------------------------------------------------_
_LisAndi Co. Ltd._, Phuket, Thailand (lisandi.com)
15/21 M.2 Viset Road, Rawai, Muang, Phuket, Thailand 83130

Mobile: +66 (0)81 606 3378
VoIP:   +49 (0)711 50 88788 50
Fax:     +49 (0)711 50 88788 50
Skype:          lisandi
Facebook:     andibecker
Google Talk/Facetime/eMail:  andi@lisandi.com

---

**Comment by yelizariev** [comment]
Which version do you use?

**Comment by yelizariev** [comment]
The same for 8.0

**Comment by yelizariev** [comment]
`Configure your company data` link works.
