### ISSUE TITLE
web_debranding: company logo disappears even it has been replaced before by the own company logo

### ISSUE THREAD

**Issue by lisandi** [itpp-labs/misc-addons#152]
When web_debranding is installed than the company logo is no more visible. This is even the case after you already changed the company logo to your own company logo.

**Comment by yelizariev** [comment]
Could you clarify where company logo is disappeared ?

**Comment by lisandi** [comment]
Hi

before installing web_debranding the odoo logo showed in website and backend left column.
By editing the company settings we changed that to be the company logo.
we than installed web_debranding and both logos disapeared. After deinstallation the Odoo logo showed up again

Andi
(Andreas Becker)

LisAndi Co. Ltd.
15/21 M.2 Viset Road
Rawai, Muang, Phuket
83130 Thailand

+66 (0)81 606 3378
+66 (0)76 38 33 08
+49 (0)711 50 88788 50 -2
+49 (0)711 50 88788 59 Fax

Skype: lisandi
GoogleTalk: andi@lisandi.com
GoogleTalk: cocopapa
Youtube: apapococ
Facebook: andibecker
Flickr: andibecker

**Comment by yelizariev** [comment]
I've checked it and haven't found nothing similar. But there could be issues with browser cache. Try to clean one after installing the module
