### ISSUE TITLE
product_image_filestore: duplicate Products

### ISSUE THREAD

**Issue by MiguelMachadoM** [itpp-labs/misc-addons#160]
When duplicate a product if you delete image of duplicate product this delete too for original product.

I think need duplicate image too with diferent ir.attachment.

**Comment by yelizariev** [comment]
Thank you for reporting

**Comment by MisterToby** [comment]
Hello sir,
is it free or are you charging for use it?

**Comment by yelizariev** [comment]
@MisterTobi it's published under gpl license

**Comment by MisterToby** [comment]
ok sir, thank you but when i installed its redirecting me to odoo store is it normal?

**Comment by yelizariev** [comment]
yes, it's convenient but paid way to install addons

**Comment by MisterToby** [comment]
so in the end we've to pay to use for it huh?

**Comment by yelizariev** [comment]
No, you don't have to pay
