### ISSUE TITLE
Disappeared And Doesn't Show up after when i clicked on Install button

### ISSUE THREAD

**Issue by MisterToby** [itpp-labs/misc-addons#174]
When i clicked on Install button it redirected me to official odoo login page and i closed the page and tried to install again but doesn't show up. what should i do? do we have to buy this module or do i miss something wrong? can you please help me out? i don't want to waste my time to remove those odoo branding stuff. Thank you very much for your great module. Keep up your great job.

**Comment by MisterToby** [comment]
i tried to delete the folder and re-cloned from git but won't worked. now i've no idea what should i do. is there anyone who can help me?

**Comment by yelizariev** [comment]
The issue is not related to module itself.
Contact us, if you need support on installation  it@it-projects.info
