### ISSUE TITLE
Remove Powered by Odoo footer on login

### ISSUE THREAD

**Issue by ghost** [itpp-labs/misc-addons#2]
Hi there

I was wondering if you could create a module to remove the "Powered by Odoo" on Login and next to it also to remove the link 'manage databases', and also the odoo footer while browsing in odoo.

I know this must be easy and i can actually remove or edit the website_templates.xml myself but the problem is i do not know how to create a module.

Can you do this?
thanks in advance

**Comment by yelizariev** [comment]
Hi, 
thank you for the idea. I'll think about it and if will have time, I could make one. But I am not sure.
I think it's better for you to create a question at forum https://www.odoo.com/forum/help-1 . Maybe there is such  module already

**Comment by yelizariev** [comment]
@Beast141 
web_debranding
website_debranding
-- delete odoo footer
