### ISSUE TITLE
[Debranding] Configuration missing after installing debranding module

### ISSUE THREAD

**Issue by auyeung112002** [itpp-labs/misc-addons#228]
Hi,

Install web_deranding module under v9c will make the "Feature" part missing, making it impossible to enable some features such as multi currency. Is the debranding module for enterprise version only?

Before installing debranding:
![image](https://cloud.githubusercontent.com/assets/8391358/16482644/41c666be-3ee3-11e6-8bf6-12fccddcbbc4.png)

After installing debranding:
![image](https://cloud.githubusercontent.com/assets/8391358/16482667/64619b94-3ee3-11e6-8f7d-ccc971fde5f7.png)

**Comment by yelizariev** [comment]
Thank you for reporting. I am going to check it

**Comment by yelizariev** [comment]
Done
Try latest version
