### ISSUE TITLE
web_debranding: TypeError: openerp.Model is not a constructor

### ISSUE THREAD

**Issue by obviousnikhil** [itpp-labs/misc-addons#238]
After installing web_debranding module, getting `TypeError: openerp.Model is not a constructor` when I tried to Reconcile bank statements from Accounting Dashboard.

![accounting dashboard 1](https://cloud.githubusercontent.com/assets/11032370/17076576/7506e81c-50d3-11e6-8539-9ea0f17b2e03.png)
![dialog error](https://cloud.githubusercontent.com/assets/11032370/17076577/7ad7cf86-50d3-11e6-9ae1-eead324a18b0.png)

**Comment by yelizariev** [comment]
Thank you for reporting. It's fixed now. Try latest version

**Comment by obviousnikhil** [comment]
You are always welcome and thanks for fixing it!
