### ISSUE TITLE
(v9) web_debranding: replase icon browser notifications

### ISSUE THREAD

**Issue by mcjulian1107** [itpp-labs/misc-addons#243]
hello Ivan

in web_debranding
I would like him to add functionality to replace the logo Odoo in browser notifications

replacing the image
addons/mail/static/img/odoo_o.png

You can replace the image as it currently does favicon

Thank you

**Comment by yelizariev** [comment]
Thanks and wait for updates

**Comment by yelizariev** [comment]
https://github.com/it-projects-llc/misc-addons/pull/246
