### ISSUE TITLE
(v9) web_debranding: options lost 

### ISSUE THREAD

**Issue by mcjulian1107** [itpp-labs/misc-addons#244]
Hello Ivan
After installing web_debranding multicurrency options and analytical accounts they were lost

on the menu
Accounting / Configuration / Settings / Features

![debranding](https://cloud.githubusercontent.com/assets/16965407/17189686/3db66922-5408-11e6-8030-82bde9da023b.png)

**Comment by yelizariev** [comment]
Are you sure, that you use latest version?
I think I've fixed it in #229
