### ISSUE TITLE
reminder_base/reminder_phonecall: no alarm_id existance verification

### ISSUE THREAD

**Issue by lexplatt** [itpp-labs/misc-addons#26]
why you don't verify if there is an alarm_id set before generating the reminder event?
With the actual behaviour any time creating a new planned call a reminder is also created, even if i didn't set one.
(reminder_base/reminder_base_models.py line 45 and line 113)

**Comment by yelizariev** [comment]
You are right. Reminders are created even if there is no reminder_alarm_ids. I've made it in order to use Calendar as an Agenda. So, you will see all planned calls for specific date at Calendar
