### ISSUE TITLE
Calendar - Two Date Column

### ISSUE THREAD

**Issue by miscs** [itpp-labs/misc-addons#27]
Hi,

I just testet your reminder_\* extensions - thank you for sharing these!

One problem for me is that reminder_crm_next_action and reminder_phonecall use different Date-Columns in Calendar View. This makes sorting events very hard.

To reproduce: 
1) Create an Opportunity -> Add Next Action with Date
2) Schedule a Phone Call with Date
3) Check Messaging -> Calendar -> List View shows two Date Columns (see screenshot)

Is there any chance to use the same Column for both reminders to support sorting?

Thanks!
Steve

<img width="876" alt="screen shot 2015-08-05 at 17 07 33" src="https://cloud.githubusercontent.com/assets/878463/9089551/f6d389f8-3b95-11e5-9b03-92a9ae0561e1.png">

**Comment by yelizariev** [comment]
It's because  Lead uses Date field (without time), while Phonecall uses Datetime

**Comment by miscs** [comment]
I thought so. I`ll think about using Datetime for Leads as well and setting a standard-time. Thanks for your feedback.
