### ISSUE TITLE
Calendar Event Lead/Opportunity opens related Record in wrong View

### ISSUE THREAD

**Issue by miscs** [itpp-labs/misc-addons#28]
I just ran into a small problem using reminder_crm_next_action

To reproduce:

1) Create an opportunity and add an next action with date
2) Open calendar -> Open created event
3) Press Button "Open Related Record"
-> Opportunity is shown in View for Leads (with Button Convert to Opportunity) but should be shown in Opportunity View

Thanks

<img width="1267" alt="screen shot 2015-08-05 at 17 07 50" src="https://cloud.githubusercontent.com/assets/878463/9089853/98ec44d6-3b97-11e5-9578-31ddc5215abc.png">

**Comment by yelizariev** [comment]
Thanks. I'll fix it.

**Comment by trojikman** [comment]
@yelizariev is this fixed?

**Comment by yelizariev** [comment]
I don't think that it's fixed

**Comment by trojikman** [comment]
@yelizariev Can you say which odoo it is?

**Comment by yelizariev** [comment]
It was reported for odoo 8, but may be still presented in odoo 13 (once we port the module :laughing: ).

I've added a note in 13.0 branch for ``reminder_crm_next_action_time`` (``reminder_crm_next_action`` maintenance  is dropped): https://github.com/itpp-labs/misc-addons/commit/a8ef8151cc968a4d3ccb8689a71e57e03f280dd7

I'd prefer to close this issue, cause there is small chance that we'll ever work on it
