### ISSUE TITLE
can't create opportunity 

### ISSUE THREAD

**Issue by yk2kus** [itpp-labs/misc-addons#30]
after installing module "reminder_crm_next_action" can't create opportunity. It gives Validate Error
Field(s) `start_datetime, stop_datetime, start_date, stop_date` failed against a constraint: Error ! End date cannot be set before start date.

not knowing which two fields are supposed to be start and end? 

same case in module "reminder_phonecall" can't create phone calls.

**Comment by yelizariev** [comment]
reminder modules set start and end dates to the same value.
Do you have any other custom modules related to calendar?
