### ISSUE TITLE
[WISHLIST] Add requirements.txt

### ISSUE THREAD

**Issue by aristobulo-eezee** [itpp-labs/misc-addons#32]
It should be great if you add requirements.txt with python dependencies. You have declared python dependencies in your modules but it's easier to install all packages using pip -r requirements.txt.

**Comment by yelizariev** [comment]
Usually module has only one external dependencies, but I think it's a good idea to have requirements.txt. I think, I'll put one to module's directory. I don't think that it's necessary to have single requirements.txt for all modules in the repo
