### ISSUE TITLE
Uncaught Exceptions Dialogs are being suppressed 

### ISSUE THREAD

**Issue by saltonmassally** [itpp-labs/misc-addons#34]
Hello @yelizariev I firstly would like to commend your work!

That said Uncaught exception thrown by the server is no longer being displayed in the js popup dialog. Inspecting this in chrome's developer console shows the following:

Uncaught TypeError: content.html is not a functioninstance.web.Dialog.include.init @ 23f952e:3950(anonymous function) @ 146c588:1092Class @ 146c588:1090instance.web.CrashManager.instance.web.Class.extend.show_error @ 23f952e:3054instance.web.CrashManager.include.show_error @ 23f952e:4165(anonymous function) @ 146c588:1092window.onerror @ 23f952e:3087

I pinpointed this error to https://github.com/yelizariev/addons-yelizariev/blob/8.0/web_debranding/static/src/js/dialog.js#L25

Looks like the code expecting jquery object however a string is being passed to the function; can we insert a check for type first and proceed according?

**Comment by yelizariev** [comment]
Thank you
