### ISSUE TITLE
Website debranding makes website title false

### ISSUE THREAD

**Issue by watermelonjuice** [itpp-labs/misc-addons#346]
As can be seen in the screenshot below the website debranding module makes the webpage title false. Inputting a new title can not be saved. Problem did not exist prior to install module. No title appears in the html code of the website.

![screenshot from 2017-01-04 05-54-39](https://cloud.githubusercontent.com/assets/5452111/21626272/bdfe8674-d242-11e6-8616-0ee14a9a489d.png)

**Comment by alexanderradahl** [comment]
Mine is just empty..

**Comment by watermelonjuice** [comment]
@yelizariev any chance we can get a fix for this?

**Comment by alexanderradahl** [comment]
Yes, it would be very helpfull.

**Comment by yelizariev** [comment]
Fixed a month ago, actually. Try latest version
https://github.com/it-projects-llc/misc-addons/commit/cc397c0ee4ce242d9f1ee35369ff7d612ab57f96

**Comment by watermelonjuice** [comment]
It is fixed now. User needs to set title in SEO for it to work.
