### ISSUE TITLE
[8.0] Impossible to send an email withtout body

### ISSUE THREAD

**Issue by BT-jmichaud** [itpp-labs/misc-addons#347]
If you are sending an email without a body (attachment only), which is normally possible, an error is triggered in **res_users_signature/res_users_signature_models.py** and the email is not sent.

The line _match = pattern.search(body, pos)_ expects a string or a buffer in body, but receive 'False' which is the correct value.

Odoo Server 8.0:vscom:ERROR:openerp.addons.mail.mail_mail:failed sending mail.mail 33 Traceback (most recent call last)
File "/home/openerp/git_repositories/odoo/addons/mail/mail_mail.py", line 302, in send     headers=headers)
File "/home/openerp/custom_addons/res_users_signature/res_users_signature_models.py", line 118, in build_email
match = pattern.search(body, pos) TypeError: expected string or buffer

**Comment by yelizariev** [comment]
Thank you for reporting. I am about to fix it
