### ISSUE TITLE
How to make Reminders and Agenda for Tasks work for project deadlines?

### ISSUE THREAD

**Issue by frozseven** [itpp-labs/misc-addons#35]
Hi Ivan,
i've been trying to work with your coding and trying to make it work for project deadline but ive been running into some problems.

my models.py is now:

from openerp import models

class project(models.Model):
    _name = 'project.project'
    _inherit = ['project.project', 'reminder']

```
_reminder_date_field = 'date'
_reminder_attendees_fields = 'user_id'
```

and my views.xml is now:

<?xml version="1.0" encoding="utf-8"?>
<openerp><data>

<record model="ir.ui.view" id="edit_project">
    <field name="model">project.project</field>
    <field name="inherit_id" ref="project.edit_project"/>
    <field name="arch" type="xml">
        <xpath expr="//field[@name='date']" position="after">
            <field name="reminder_alarm_ids" widget="many2many_tags" attrs="{'readonly':[('date','=',False)]}" string="Reminders"/>
        </xpath>
    </field>
</record>

</data></openerp>

BUT every time i try to select an end date it gives me an error:

  File "/opt/odoo8/odoo/addons/reminder_base/reminder_base_models.py", line 93, in _do_update_reminder
    field = self._columns[field_name]
KeyError: 'u'

---- could you please help me out? ----

**Comment by yelizariev** [comment]
Try this:

```
_reminder_attendees_fields = ['user_id']
```

**Comment by frozseven** [comment]
Hi Ivan,

i just tried but it still gives the same error. :(

**Comment by yelizariev** [comment]
don't forget to restart odoo

**Comment by frozseven** [comment]
i've restarted odoo... but still not working

**Comment by yelizariev** [comment]
Try  remove *.pyc files

**Comment by frozseven** [comment]
i've did so..but still not working :(

**Comment by frozseven** [comment]
looks like it can't find a field name user_id in projects which does not seem to be in projects. but in projects form there is a user_id. just can't figure out where its coming from
