### ISSUE TITLE
product_without_taxes - price calculation

### ISSUE THREAD

**Issue by vkanev** [itpp-labs/misc-addons#36]
Hello,
The module is great! It saved me. One thing I saw and I think it will be better to be fixed.

I had a problem with the calculated price without taxes. In your code you have the following line:
                line.price_unit \* (1-(line.discount or 0.0)/100.0),
In it you calculate the price with the discount. Although in a report (proposal, invoice, etc.) "discount" column is positioned after the "unit price" column although the discount is already calculated. If you remove the discount from the calculation, everything will be logically ordered in a line:
description, qty, uom, unit price with taxes, unit price without taxes, taxes, discount, summary with discount.

Now with your module the line looks like:
description, qty, uom, unit price with taxes, unit price with discount and without taxes, taxes, discount, summary with discount;
which is a little confusing.

I hope I explained it well enough.

The lines that in my opinion should be changed are line 14, line 33 in models.py file.

I have made the change in my local installation and everything is just working fine and is in my opinion more logical looking at the columns' order.

Anyway, great work done!

**Comment by yelizariev** [comment]
Hi,
at first glance I think you are right. Could you prepare PR? You need to click Fork, edit files and then click "Compare" or " Create pull request".

**Comment by vkanev** [comment]
Hi,

I will use github interface and later I will add the pull request. 
Please check before approving.

Greetings,
Vihren

**Comment by yelizariev** [comment]
https://github.com/yelizariev/addons-yelizariev/pull/37

**Comment by yelizariev** [comment]
Thank you
