### ISSUE TITLE
(v10) error in views.xml while installation of project_kanban_customer

### ISSUE THREAD

**Issue by m3dbedb** [itpp-labs/misc-addons#398]
While istalling a module odoo say someting wrong with line 4 of project_kanban_customer/views.xml file.
Also line 13 of project_kanban_customer/__openerp__.py
is  'installable': False
При установке выскакивает ошибка со ссылкой на 4 строку файла project_kanban_customer/views.xml
Ещё заметил, что в файле project_kanban_customer/__openerp__.py настройка 'installable': False
`File "C:\Program Files (x86)\Odoo 10.0\server\odoo\models.py", line 1074, in _validate_fields
ParseError: "Error while validating constraint

\u042d\u043b\u0435\u043c\u0435\u043d\u0442 '<xpath expr="//h4">' \u043d\u0435 \u043c\u043e\u0436\u0435\u0442 \u043d\u0430\u0445\u043e\u0434\u0438\u0442\u0441\u044f \u0432 \u0440\u043e\u0434\u0438\u0442\u0435\u043b\u044c\u0441\u043a\u043e\u043c \u0432\u0438\u0434\u0435

\u041e\u0448\u0438\u0431\u043a\u0430 \u043a\u043e\u043d\u0442\u0435\u043a\u0441\u0442\u0430:
\u041f\u0440\u043e\u0441\u043c\u043e\u0442\u0440 `project.project kanban`
[view_id: 737, xml_id: \u041d\u0435\u0434\u043e\u0441\u0442\u0443\u043f\u043d\u043e, model: project.project, parent_id: 522]
None" while parsing file:///c:/Program%20Files%20(x86)/Odoo%2010.0/server/custom/project_kanban_customer/views.xml:4, near
record model="ir.ui.view" id="view_project_kanban"`

**Comment by yelizariev** [comment]
I developed this module for odoo 8.0, so installation in 10.0 can have errors.
The module is not ported yet

**Comment by Ramil-Mukhametzyanov** [comment]
DECODING
--------
Элемент '' не может находится в родительском виде
Ошибка контекста:
Просмотр project.project kanban
[view_id: 737, xml_id: Недоступно, model: project.project, parent_id: 522]

**Comment by trojikman** [comment]
Module is not installable in odoo 10.0
