### ISSUE TITLE
Reminder used with the OCA Mass Edit

### ISSUE THREAD

**Issue by alexanderradahl** [itpp-labs/misc-addons#415]
Hello!

I'm facing some problems. I want to add reminders to all my tasks in a project. So I setup a Mass Edit action from the OCA Mass Edit module.
But this doesn't work, it assigns a task to me (it should be for a different user) and the other one I edited along side this one just gets the name "TMP NAME"
Take a look here: https://cl.ly/2X3f302M1i22

Odoo 10 Community Edition

**Comment by ilmir-k** [comment]
Fixed. Thank you
