### ISSUE TITLE
[project_task_subtask] 8.0 module for v10.0

### ISSUE THREAD

**Issue by blutecsolutions** [itpp-labs/misc-addons#433]
Hello all,

Is there a migration ongoing for the module: project_task_subtask to v10.0
https://www.odoo.com/apps/modules/8.0/project_task_subtask/

Thanks

**Comment by yelizariev** [comment]
@blutecsolutions yes, we did some migration updates, but haven't finished yet due to time shortage.

@GabbasovDinar Can you publish current progress?

**Comment by yelizariev** [comment]
Actually, I mistook this module with another one. 
We, haven't started to work on project_task_subtask migration yet. Sorry

**Comment by ilmir-k** [comment]
@blutecsolutions 

Glad to inform that we migrated the module project_task_subtask to v10.0
