### ISSUE TITLE
[Debranding][10] "new_website" setting has no effect

### ISSUE THREAD

**Issue by auyeung112002** [itpp-labs/misc-addons#435]
Installed web_debranding in odoo 10c, the website url in the "Powered by" part doesn't respect the setting in ir.config.parameter. It still links to www.odoo.com
![image](https://user-images.githubusercontent.com/8391358/26961347-9b36c5b8-4d10-11e7-812d-a510349c6c29.png)

**Comment by yelizariev** [comment]
new_website has a different meaning. It replaces examples that use odoo.com website, e.g. in field placeholders. It doesn't replace the Powered by or any other links

"Powered by" is actually removed by web_debranding, so you shall not see it at all. Something wrong with your installation
