### ISSUE TITLE
Error installing

### ISSUE THREAD

**Issue by tomhydra** [itpp-labs/misc-addons#449]
TypeError: <class 'odoo.addons.web_debranding.models.publisher_warranty_contract.publisher_warranty_contract'> transforms the abstract model 'publisher_warranty.contract' into a non-abstract model. That class should either inherit from AbstractModel, or set a different '_name'.

**Comment by yelizariev** [comment]
It actually uses Abstract model. https://github.com/it-projects-llc/misc-addons/blob/10.0/web_debranding/models/publisher_warranty_contract.py
You probably use modified version of the module
