### ISSUE TITLE
Mail footer on project issue

### ISSUE THREAD

**Issue by gdlin** [itpp-labs/misc-addons#47]
Hi

Thanks for your work ! 

I have installed the mail_footer addons, and with the invoices I have no problems, but when I send an email from the Project Issue module, I get a ", shortcut to Project Issue XXXXX" on the footer of my email. Is there anything that can be done to solve that?

Thanks.

**Comment by yelizariev** [comment]
Hi
I guess it's a special footer by project_issue or by email template

Could you provide exact value for footer?

**Comment by gdlin** [comment]
Hi, the text is the following:

, acceso directo a Project Issue 12test
http://track.gestiondeturnos.net/track/click/30610513/odoo.zonedevelopments.com.ar?p=eyJzIjoiUS02emlsRHZUNlZWVDdlZnYwbGlVRXhRT09JIiwidiI6MSwicCI6IntcInVcIjozMDYxMDUxMyxcInZcIjoxLFwidXJsXCI6XCJodHRwOlxcXC9cXFwvb2Rvby56b25lZGV2ZWxvcG1lbnRzLmNvbS5hclxcXC93ZWJcXFwvc2lnbnVwP3JlZGlyZWN0PSUyRndlYiUyM2FjdGlvbiUzRG1haWwuYWN0aW9uX21haWxfcmVkaXJlY3QlMjZtb2RlbCUzRHByb2plY3QuaXNzdWUlMjZpZCUzRDI0JnRva2VuPVk2VnljRnBvb3pwdkZvTHFXbDlIJmRiPXpkZ19ndG5cIixcImlkXCI6XCJiYTYyZjBmMGQ2YmE0OGY3ODEwNjE3YmQ0YmQ1MzVhOVwiLFwidXJsX2lkc1wiOltcIjhmM2FjMDQ4NDQ2OGVjZTU2NDg2ODA4NmZiN2EyMDM3NDBiZWMyNzlcIl19In0

My odoo is in spanish, "acceso directo" means shortcut/link. The issue name
was _12test_

**Comment by yelizariev** [comment]
Are you sure that you have installed mail_delete_access_link addon?

**Comment by gdlin** [comment]
yes, I have the following installed:

mail_delete_access_link
mail_delete_odoo_footer
mail_delete_sent_by_footer

it's strange !

**Comment by yelizariev** [comment]
@gdlin 
could you try following:
-  edit mail_delete_access_link/**openerp**.py file:
  
  ```
  -    'depends' : ['mail'],
  +    'depends' : ['mail', 'portal'],
  ```
- restart odoo
- "Update module list"
- update mail_delete_access_link module

**Comment by yelizariev** [comment]
@gdlin 
Also, could you tell me do you have other external modules that extend project issue module?
