### ISSUE TITLE
project_task_subtask [10.0]: reviewers_ids not global

### ISSUE THREAD

**Issue by mgielissen** [itpp-labs/misc-addons#482]
project_task_subtask.py:

            r.message_post(type='comment',
                           subtype=subtype,
                           body=body,
                           reviewer_ids=reviewer_ids)

Correct:

            r.message_post(message_type='comment',
                           subtype=subtype,
                           body=body,
                           partner_ids=partner_ids)

**Comment by ilmir-k** [comment]
@iledarn and @manawi review it please

**Comment by ilmir-k** [comment]
@mgielissen 
Thank you for reporting this. It was solved.

**Comment by yelizariev** [comment]
Fixed in https://github.com/it-projects-llc/misc-addons/pull/488
