### ISSUE TITLE
[11.0][CI] ir_attachment_s3: request for unittests [$40]

### ISSUE THREAD

**Issue by iledarn** [itpp-labs/misc-addons#515]
The 11.0 branch's ir_attachment_s3 module should have python tests
https://github.com/it-projects-llc/misc-addons/tree/11.0/ir_attachment_s3

##### Thorough specification of the task is the following:
* Make sure that `s3.condition` system parameter is empty or includes `res.users` model
* Find Demo User's `image` binary field attachment in the `ir.attachment` model records. Make sure that its type is not `url`.
* write in the `image` field of the Demo User into `res.users` model
* after the write function succeeds, once again find the `image` binary field attachment record and make sure that now it is of `url` type and has the url in its `url` field

##### Additional information
Python tests instruction is here https://odoo-development.readthedocs.io/en/latest/qa/python/index.html

**Comment by yelizariev** [comment]
Work with s3 server must be emulated via Mock. Find examples in odoo source: https://github.com/odoo/odoo/search?l=Python&q=mock&type=&utf8=%E2%9C%93

**Comment by yelizariev** [comment]
Also, test must check, that ``s3.condition`` equal to ``[('res_model', 'in', ['res.users'])]``  works only with ``res.users`` and doesn't change behavior for other models (e.g. ``res.company``)

**Comment by yelizariev** [comment]
The modules are heavily refactored in v13 and the scenarios of this issue are  mostly obsolete
