### ISSUE TITLE
reminder_task_deadline

### ISSUE THREAD

**Issue by kjmtjen2** [itpp-labs/misc-addons#520]
ParseError: "L\u1ed7i khi th\u1ea9m \u0111\u1ecbnh t\xednh r\xe0ng bu\u1ed9c

Element '<xpath expr="//field[@name='date_deadline']">' cannot be located in parent view

Ng\u1eef c\u1ea3nh khi l\u1ed7i:
Xem `project.task form`
[view_id: 1670, xml_id: n/a, model: project.task, parent_id: 1594]
None" while parsing /test/custom/addons/reminder_task_deadline/views.xml:4, near
<record model="ir.ui.view" id="view_task_form2">
    <field name="model">project.task</field>
    <field name="inherit_id" ref="project.view_task_form2"/>
    <field name="arch" type="xml">
        <xpath expr="//field[@name='date_deadline']" position="after">
            <field name="reminder_alarm_ids" widget="many2many_tags" attrs="{'readonly':[('date_deadline','=',False)]}" string="Reminders"/>
        </xpath>
    </field>
</record>

**Comment by Ramil-Mukhametzyanov** [comment]
DECODING
-----------------
ParseError: "Lỗi khi thẩm định tính ràng buộc"

Element '' cannot be located in parent view
Ngữ cảnh khi lỗi:
Xem project.task form
[view_id: 1670, xml_id: n/a, model: project.task, parent_id: 1594]
None" while parsing /test/custom/addons/reminder_task_deadline/views.xml:4, near

project.task

**Comment by Ramil-Mukhametzyanov** [comment]
Version odoo is 9.0 or below:  reminder_task_deadline/views.xml

Odoo versions 9.0 or below are not supported.
Phiên bản Odoo 9.0 trở xuống không được hỗ trợ.
