### ISSUE TITLE
[8.0] Модуль autostaging_project_task рушит уведомления для задач

### ISSUE THREAD

**Issue by suvit** [itpp-labs/misc-addons#537]
Модуль autostaging_project_task перекрывает все родные subtypes у project.task
Из-за этого перестают приходить уведомления о создании задачи и другие.

Решаем у себя так

```
class FixedTask(Model):
    _inherit = 'project.task'
    _track = Task._track
    _track['stage_id'].update(ProjectTaskAutostaging._track['stage_id'])
```

**Comment by yelizariev** [comment]
Interesting trick.
Does it work when there is another module that adds another subtype in the same way?

**Comment by suvit** [comment]
Там вообще не продумано сделано, по идее надо в mail.thread перекрыть Model._build_model и собрать все _track в один словарь.
Сейчас любое _inherit с локальным аттрибутом класса _track, убивает все subtype в базовом _track

**Comment by yelizariev** [comment]
В новых версиях примерно так и сделано. Там метод наследовать нужно

**Comment by yelizariev** [comment]
@iledarn не помнишь какой метод?

**Comment by trojikman** [comment]
Versions below odoo 10 are not supported
