### ISSUE TITLE
base_deatils and product_details implementation Question

### ISSUE THREAD

**Issue by bunhin** [itpp-labs/misc-addons#585]
I would like to implement 2 modules: base details and product_details, follow the instruction available in each modules as reference for the implementation, also try to installs the product_details module,  but i only have blank  Details field (can not select anything or create the the details as similar to other m2one fields.

Is the product_details module miss the details model or still need to be created (or need to extend the modules) in order to see how it will work? 
I am very new to coding, please give a more lines of clue or guide to implement it correctly. As example with this product_details....how to add and edit the details then?

Thanks and regards,

**Comment by yelizariev** [comment]
Hi,
you need to inherit ``_model_selection``. I've updated the documentation https://github.com/it-projects-llc/misc-addons/blob/10.0/product_details/doc/index.rst
