### ISSUE TITLE
[]website_files] does block switching of image selection 

### ISSUE THREAD

**Issue by lucode** [itpp-labs/misc-addons#7]
Hi,

First thanks for the great module.

There is a issue with website_file. An all my instances installing the module does block switching of image selection.
When I click on the right side button  "Next->" the cursor turns to a stop symbol and I can't turn to the next page of images.
![image](https://cloud.githubusercontent.com/assets/2928740/7954291/79a33ef4-09ce-11e5-87e6-cf982d767119.png)

When I deinstall the module everything is fine again.

cheers
Lucas

**Comment by yelizariev** [comment]
Hi,

 thanks for reporting. Try this update
