### ISSUE TITLE
Uncaught TypeError: Cannot read property 'attrs' of undefined in barcode_widget Module

### ISSUE THREAD

**Issue by JohnOdoo** [itpp-labs/misc-addons#746]
Hi, 
Im using barcode_widget module for odoo v8. But it showing error. Can you please help on this

![Screenshot from 2019-05-18 13:32:42](https://user-images.githubusercontent.com/29749049/57966568-6f795a00-7971-11e9-9dba-8ada3d219a8c.png)

i have created a new field <barcode>
<field name="ean13" position="after">
					<field name="barcode" widget="BarCode128" />
				</field>
Thanks,

**Comment by trojikman** [comment]
Hello, unfortunately odoo versions below 10.0 are not supported.
