### ISSUE TITLE
Web Debranding Decode Issue

### ISSUE THREAD

**Issue by sm2x** [itpp-labs/misc-addons#762]
How do you address this decode error:
ir_translation.py AttributeError: 'str' object has no attribute 'decode' - - -

I believe this is a migration issue to Python3?
def debrand_bytes(env, source):
    return bytes(debrand(env, source.decode('utf-8')), 'utf-8')

**Comment by yelizariev** [comment]
Are you sure that you use latest version of the module? Which odoo version do you use and when do you see the error?

**Comment by sm2x** [comment]
Odoo 11
Any web access produces this error.

**Comment by blaggacao** [comment]
Confirm, `concat_xml` does return unicode in the first position, see: https://github.com/odoo/odoo/blob/1f627dcf576d91bb093b7229441323390af91449/addons/web/controllers/main.py#L224

**Comment by trojikman** [comment]
Apparently it fixed here https://github.com/itpp-labs/misc-addons/commit/549c881f8a1212f7800b8b1156e95d78a328ca7b
