### ISSUE TITLE
Missing dependency?

### ISSUE THREAD

**Issue by blaggacao** [itpp-labs/misc-addons#771]
https://github.com/it-projects-llc/misc-addons/blob/3466e508d8ab4eab2adf578ba3930990895b5596/web_calendar_quick_navigation/__manifest__.py#L8

Where can I find this dependency. It can't be identified in my intent to build up a DAG for a project. Am I missing something?

**Comment by yelizariev** [comment]
:smile: https://github.com/odoo/odoo/tree/8.0/addons/web_calendar

**Comment by blaggacao** [comment]
It's gone on v11.

**Comment by blaggacao** [comment]
But: https://github.com/it-projects-llc/misc-addons/blob/11.0/web_calendar_quick_navigation/__manifest__.py#L8

**Comment by trojikman** [comment]
This module worked in 8.0 and is not ported to the rest.
