### ISSUE TITLE
web_debranding: false error in tests

### ISSUE THREAD

**Issue by yelizariev** [itpp-labs/misc-addons#818]
https://travis-ci.com/it-projects-llc/misc-addons/jobs/241958070

My guess is that menu is collapsed with project_timelog installed. So, we need to add extra step in the tests

**Comment by trojikman** [comment]
> https://travis-ci.com/it-projects-llc/misc-addons/jobs/241958070

This link does not work, in which version does the error appear?

**Comment by yelizariev** [comment]
https://travis-ci.com/itpp-labs/misc-addons/jobs/241958070

**Comment by yelizariev** [comment]
The logs are lost and the issue is not reproduced on the latest travis
