### ISSUE TITLE
[INFO] mail_partner_lang

### ISSUE THREAD

**Issue by rafaelbn** [itpp-labs/misc-addons#88]
Hi @yelizariev ,

This module: https://github.com/yelizariev/addons-yelizariev/tree/8.0/mail_partner_lang

What fix exactly fix it? could you give me the link?

cc @pedrobaeza @antespi @Yajo @sergio-incaser @carlos-incaser

Thanks

**Comment by yelizariev** [comment]
Hi @rafaelbn 
It adds lang value to context
https://github.com/yelizariev/addons-yelizariev/commit/4c1cc4f92e1e2ff95b2ebce59925aef5fcc7f2ac

**Comment by rafaelbn** [comment]
Could you purpose to Odoo in a PR to fix this?:
- https://github.com/odoo/odoo/issues/7896
- https://github.com/OCA/social/issues/26

**Comment by yelizariev** [comment]
@rafaelbn I wrote this module one year ago... I don't have an inspiration to prepare a PR now. I'd not mind if somebody takes my fix and create PR.

**Comment by rafaelbn** [comment]
OK, thanks @yelizariev we will do it.
Just the question: functionality talking, what do you fix adding lang value to context?
Before reporting Odoo I need to test it.

**Comment by yelizariev** [comment]
As I remember it makes email body, subject etc translatable
