### ISSUE TITLE
ir_attachment_s3 12.0

### ISSUE THREAD

**Issue by Ramil-Mukhametzyanov** [itpp-labs/misc-addons#953]
Redirected from a client:
"
Hi, i installed the module and new files are been uploaded to S3, the url system works fine, but when uploading existing attachments, they are indeed uploaded to AWS but the url is not set automatically in the attachment in Odoo, making really hard to impossible to match the file in the bucket with every attachment, is this the right behavior or something is failing?, also when trying to update the ir.attachment settings to S3 (from save as original link) fallbacks to "Save as original link", I don't know if this is part of the problem in the uploading to s3 problem
"

**Comment by yelizariev** [comment]
Можешь написать что ожидается и что есть сейчас?

**Comment by trojikman** [comment]
Feel free to reopen with more details
